# Single Layer Perceptron

In [47]:
import numpy as np

In [48]:
class Perceptron(object):
  def __init__(self, input_size, lr = 1, epochs = 10):
    self.W = np.zeros(input_size + 1)
    self.epochs = epochs
    self.lr = lr
  
  def activation_fn(self, x):
    return 1 if x >= 0 else 0

  def predict(self, x):
    z = self.W.T.dot(x)
    a = self.activation_fn(z)
    return a

  def fit(self, X, d):
    for _ in range(self.epochs):
      for i in range(d.shape[0]):
        x = np.insert(X[i], 0, 1)
        y = self.predict(x)
        e = d[i] - y
        self.W = self.W + self.lr * e * x

  def test(self, X, d):
    p = np.zeros(d.shape[0])
    print("Input\tExpected\tPredicted")
    for i in range(d.shape[0]):
      x = np.insert(X[i], 0, 1)
      t = self.predict(x)
      print(X[i], " ", d[i], "\t\t", t)
      p[i] = t
    return p

### AND Gate

In [49]:
# AND Gate
if __name__ == '__main__':
  X = np.array([
                [0, 0],
                [0, 1],
                [1, 0],
                [1, 1]
  ])
  d = np.array([0, 0, 0, 1])
  print("AND Gate with Single Layer Perceptron")
  perceptron = Perceptron(input_size = 2)
  perceptron.fit(X, d)
  print("Trained Weights: ", perceptron.W)
  p = perceptron.test(X, d)

AND Gate with Single Layer Perceptron
Trained Weights:  [-3.  2.  1.]
Input	Expected	Predicted
[0 0]   0 		 0
[0 1]   0 		 0
[1 0]   0 		 0
[1 1]   1 		 1


### OR Gate

In [50]:
# OR Gate
if __name__ == '__main__':
  X = np.array([
                [0, 0],
                [0, 1],
                [1, 0],
                [1, 1]
  ])
  d = np.array([0, 1, 1, 1])
  print("OR Gate with Single Layer Perceptron")
  perceptron = Perceptron(input_size = 2)
  perceptron.fit(X, d)
  print("Trained Weights: ", perceptron.W)
  p = perceptron.test(X, d)

OR Gate with Single Layer Perceptron
Trained Weights:  [-1.  1.  1.]
Input	Expected	Predicted
[0 0]   0 		 0
[0 1]   1 		 1
[1 0]   1 		 1
[1 1]   1 		 1


# Multi Level Perceptron

In [51]:
class mlp(object):
  def __init__(self, input_dim, hidden_dim, output_dim, epochs = 10000, lr = 1.0):
    self.W1 = np.random.random((input_dim, hidden_dim))
    self.W2 = np.random.random((hidden_dim, output_dim))
    self.epochs = epochs
    self.lr = lr

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def sigmoid_derivative(self, sx):
    return sx * (1 - sx)

  def cost(self, predicted, truth):
    return truth - predicted

  def fit(self, X, Y):
        for epoch_n in range(self.epochs):
            layer0 = X

            # forward propagation
            layer1 = self.sigmoid(np.dot(layer0, self.W1))
            layer2 = self.sigmoid(np.dot(layer1, self.W2))

            # back propagation (Y -> Layer2)
            layer2_error = self.cost(layer2, Y)
            layer2_delta = layer2_error * self.sigmoid_derivative(layer2)

            # back propagation (Layer2 -> Layer1)
            layer1_error = np.dot(layer2_delta, self.W2.T)
            layer1_delta = layer1_error * self.sigmoid_derivative(layer1)

            # update weights
            self.W2 += self.lr * np.dot(layer1.T, layer2_delta)
            self.W1 += self.lr * np.dot(layer0.T, layer1_delta)
        
  def predict(self, X, Y):
        p = []
        q = []
        for x, y in zip(X, Y):
            layer1_prediction = self.sigmoid(np.dot(self.W1.T, x))
            prediction = layer2_prediction = self.sigmoid(np.dot(self.W2.T, layer1_prediction))
            print(prediction, "\t", int(prediction > 0.5), "\t\t\t", y)
            p.append(prediction)
        return p
    
  def weights(self):
        print("W1 = ", self.W1)
        print("W2 = ", self.W2)

### XOR Gate

In [52]:
xor_input = np.array([
                [0, 0],
                [0, 1],
                [1, 0],
                [1, 1]
  ])
xor_output = np.array([[0, 1, 1, 0]]).T

X = xor_input
Y = xor_output

print("Multi Layer Perceptron for XOR Gate")
perceptron = mlp(input_dim = 2, hidden_dim = 5, output_dim = 1)
perceptron.fit(X, Y)
print("Fitted Weights: ")
perceptron.weights()
print("Model's Prediction")
print("Output Value\tRounded Up Output\tExpected Value")
p = perceptron.predict(X, Y)

Multi Layer Perceptron for XOR Gate
Fitted Weights: 
W1 =  [[-0.97783649  6.79120311  5.70149054  1.97617972 -3.5294332 ]
 [-0.84739682 -3.25204112  5.6726249  -0.98366558  7.27426187]]
W2 =  [[-3.04226043]
 [-8.26266439]
 [15.87940663]
 [-2.75622782]
 [-9.77465804]]
Model's Prediction
Output Value	Rounded Up Output	Expected Value
[0.01837529] 	 0 			 [0]
[0.98347994] 	 1 			 [1]
[0.9827486] 	 1 			 [1]
[0.01579106] 	 0 			 [0]


### Using dataset

In [53]:
class mlp(object):
  def __init__(self, input_dim, hidden_dim, output_dim, epochs = 10000, lr = 1.0):
    self.W1 = np.random.random((input_dim, hidden_dim))
    self.W2 = np.random.random((hidden_dim, output_dim))
    self.epochs = epochs
    self.lr = lr

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def sigmoid_derivative(self, sx):
    return sx * (1 - sx)

  def cost(self, predicted, truth):
    for i in range(len(predicted)):
        return 0 if truth[i] == predicted[i] else 1

  def fit(self, X, Y):
        for epoch_n in range(self.epochs):
            layer0 = X

            # forward propagation
            layer1 = self.sigmoid(np.dot(layer0, self.W1))
            layer2 = self.sigmoid(np.dot(layer1, self.W2))

            # back propagation (Y -> Layer2)
            layer2_error = self.cost(layer2, Y)
            layer2_delta = layer2_error * self.sigmoid_derivative(layer2)

            # back propagation (Layer2 -> Layer1)
            layer1_error = np.dot(layer2_delta, self.W2.T)
            layer1_delta = layer1_error * self.sigmoid_derivative(layer1)

            # update weights
            self.W2 += self.lr * np.dot(layer1.T, layer2_delta)
            self.W1 += self.lr * np.dot(layer0.T, layer1_delta)
        
  def predict(self, X, Y):
        p = []
        q = []
        for x, y in zip(X, Y):
            layer1_prediction = self.sigmoid(np.dot(self.W1.T, x))
            prediction = layer2_prediction = self.sigmoid(np.dot(self.W2.T, layer1_prediction))
            print(prediction, "\t", int(prediction > 0.5), "\t\t\t", y)
            p.append(prediction)
        return p
    
  def weights(self):
        print("W1 = ", self.W1)
        print("W2 = ", self.W2)

In [54]:
%cd "/home/mona/3074 ML Lab/Datasets"

/home/mona/3074 ML Lab/Datasets


In [55]:
import pandas as pd

# read data
data = pd.read_csv('iris_data.csv')

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train, x_test, y_train, y_test = train_test_split(np.array(data)[:, :-1], np.array(data)[:, -1], test_size = 0.20)
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [57]:
print("Multi Layer Perceptron for Iris dataset")
perceptron = mlp(input_dim = 4, hidden_dim = 5, output_dim = 1)
perceptron.fit(x_train, y_train)
print("Fitted Weights: ")
perceptron.weights()
print("Model's Prediction")
print("Output Value\tRounded Up Output\tExpected Value")
p = perceptron.predict(x_test, y_test)

Multi Layer Perceptron for Iris dataset


/home/mona/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  app.launch_new_instance()


Fitted Weights: 
W1 =  [[-0.19603998 -0.53179729 -0.69940481  0.19689996  0.54224889]
 [-0.13286565  0.39914312  0.83186882  0.80475239 -0.23030045]
 [-0.00849795  0.28708687 -0.68534733 -0.37075754  0.75715295]
 [ 0.32547601 -0.0239827  -0.6030347   0.39246717  0.39589072]]
W2 =  [[8.52287903]
 [7.94341417]
 [8.90046613]
 [7.66362679]
 [7.71622188]]
Model's Prediction
Output Value	Rounded Up Output	Expected Value
[1.] 	 1 			 setosa
[1.] 	 1 			 setosa
[0.99999998] 	 1 			 versicolor
[1.] 	 1 			 setosa
[0.99999999] 	 1 			 virginica
[1.] 	 1 			 virginica
[0.9999999] 	 1 			 versicolor
[1.] 	 1 			 virginica
[1.] 	 1 			 virginica
[1.] 	 1 			 setosa
[0.99999999] 	 1 			 versicolor
[1.] 	 1 			 versicolor
[1.] 	 1 			 setosa
[1.] 	 1 			 setosa
[1.] 	 1 			 versicolor
[1.] 	 1 			 setosa
[0.99999993] 	 1 			 versicolor
[1.] 	 1 			 virginica
[0.99999999] 	 1 			 virginica
[0.99999991] 	 1 			 versicolor
[0.99999999] 	 1 			 versicolor
[0.99999997] 	 1 			 virginica
[1.] 	 1 			 virgi

# Spot
Train a single layer perceptronto classify whether a fruit presented to the perceptron is going to be liked by a certain  person or not, based on three features attributed to the  presented fruit: its  taste  (whether  it  is  sweet  or  not),  its  seeds  (whether  they  are  edible  or  not)  and  its skin (whether it is edible or not). Consider the following table for the inputs and the  target output of the  perceptron.  Since  there  are  three  (binary)  input  values  (taste,  seeds  and  skin)  and  one (binary) target output, construct a single-layer perceptronwith three inputs and one output.

In [58]:
import numpy as np

In [67]:
class Perceptron(object):
  def __init__(self, input_size, lr = 1, epochs = 20):
    self.W = np.zeros(input_size + 1)
    self.epochs = epochs
    self.lr = lr
  
  def activation_fn(self, x):
    return 1 if x >= 0 else 0

  def predict(self, x):
    z = self.W.T.dot(x)
    a = self.activation_fn(z)
    return a

  def fit(self, X, d):
    for _ in range(self.epochs):
      for i in range(d.shape[0]):
        x = np.insert(X[i], 0, 1)
        y = self.predict(x)
        e = d[i] - y
        self.W = self.W + self.lr * e * x

  def test(self, X, d):
    p = np.zeros(d.shape[0])
    print("Input\tExpected\tPredicted")
    for i in range(d.shape[0]):
      x = np.insert(X[i], 0, 1)
      t = self.predict(x)
      print(X[i], " ", d[i], "\t\t", t)
      p[i] = t
    return p

In [68]:
%cd "/home/mona/3074 ML Lab/Datasets"

/home/mona/3074 ML Lab/Datasets


In [74]:
import pandas as pd

# read data
data = pd.read_csv('fruits.csv')
data

Fruit  Taste  Seeds  Skin  Target
0       Banana      1      1     0       1
1         Pear      1      0     1       1
2        Lemon      0      0     0       0
3   Strawberry      1      1     1       1
4  Green Apple      0      0     1       0

In [75]:
# classifying if fruits would be liked
if __name__ == '__main__':
  X = np.array(data.iloc[:, 1:4])
  d = np.array(data.iloc[:, -1])

[[1 1 0]
 [1 0 1]
 [0 0 0]
 [1 1 1]
 [0 0 1]] [1 1 0 1 0]


In [76]:
  print("Classifying Fruit Preferences with Single Layer Perceptron")
  perceptron = Perceptron(input_size = 3)
  perceptron.fit(X, d)
  print("Trained Weights: ", perceptron.W)
  p = perceptron.test(X, d)

Classifying Fruit Preferences with Single Layer Perceptron
Trained Weights:  [-1.  1.  1.  0.]
Input	Expected	Predicted
[1 1 0]   1 		 1
[1 0 1]   1 		 1
[0 0 0]   0 		 0
[1 1 1]   1 		 1
[0 0 1]   0 		 0
